server_host: "irc.freenode.net"
server_port: 6667
bot_nickname: pmxbot
log_channels:
    - "#pmxbot"
other_channels:
    - "#pmxbot2"
inane_channel: "#pmxbot"
# database should be something like a MongoDB URI (mongodb://localhost)
#  or sqlite URI (sqlite:path/filename)
database: sqlite:pmxbot.sqlite
places: ["Palo Alto, CA", "Canton, OH", "Washington, DC", "London, England"]
lunch_choices:
    PA: ["Pasta?", "Thaiphoon", "Pluto's", "Penninsula Creamery", "Kan Zeman"]
feed_interval: 15 #minutes
feeds:
    - name    : "pmxbot bitbucket"
      channel : "#botone"
      linkurl : "http://bitbucket.org/yougov/pmxbot"
      url     : "http://bitbucket.org/yougov/pmxbot"
    - name    : "pmxbot on twitter"
      channel : "#bottwo"
      linkurl : "http://search.twitter.com/search?q=pmxbot"
      url     : "http://search.twitter.com/search.atom?q=pmxbot"
librarypaste: http://a.libpa.st/

web_base: /
web_port: 8080
web_host: 0.0.0.0
#logo: /pmxbot.png

# ping the server every 30 seconds to recover from dropped connections
TCP keepalive: 30 seconds

# set a rate limit on outgoing messages in messages per second
message rate limit: 2.5
